apiVersion: v1
kind: Service
metadata:
  name: triton-inference-server
spec:
  type: NodePort
  ports:
  - port: 90
    targetPort: 8090
  selector:
    app: triton-inference-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-inference-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-inference-server
  template:
    metadata:
      labels:
        app: triton-inference-server
    spec:
      containers:
      - name: triton
        image: nvcr.io/nvidia/tritonserver:21.12-py3:1.8
        ports:
        - containerPort: 8090
